CREATE TABLE contact (
  number integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(6),
  givenname varchar(20),
  middleinitial varchar(1),
  surname varchar(23),
  streetaddress varchar(100),
  city varchar(100),
  state varchar(22),
  zipcode varchar(15),
  emailaddress varchar(100),
  telephonenumber varchar(25),
  birthday varchar(10),
  occupation varchar(70),
  company varchar(70)
);